### ISSUE TITLE
Decide a time for everyday discussion

### ISSUE THREAD

**Issue by MeTushar** [chingu-voyage3/toucans-29#8]
It's not related to ACT-1 but we have to discuss it any way. This is a serious issue that we can't ignore. So, adding this to milestone.

**Comment by leonardusriyo** [comment]
i think it will be best if we discuss on the morning and night, especially weekend that we all have time to do this project.

**Comment by zackmym** [comment]
i am one hour infront of leonard so am ok with the timing besides i used have classes at night...

**Comment by Sruthisarav** [comment]
It will be a bit difficult in the morning because of timezone difference. For example, if we meet up at 9am my time, it might be 6.30am or 8 am for you. So, I think evenings are better. If we need to meet up twice, we can meet up in the early afternoon.

**Comment by leonardusriyo** [comment]
it was decided that we will meet up on slack on 6 PM UTC+7, right? the additional meeting will be discussed later
